name: Semantic PR Check

on:
  pull_request:
    branches: [dev]
    types:
      - opened
      - edited
      - synchronize
      - reopened
jobs:
  main:
    name: Semantic PR Check
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
